### PR TITLE
fix Batch update feature

### LINKED ISSUE #594: Batch update form issues
It is possible to enter invalid data to batch update form:
validate

Later update delay job will fail on postgresql exception caused by postgresql type validation.
We should to check user input before delay job create.

and the feature 'Update batch' should be removed from the invoices and payment pages

### PR DESCRIPTION
**Pull request by Ivanov-Anton**
closes #594

### CODE REVIEW

File: lib/resource_dsl/acts_as_async_update.rb [hunk 1]
```diff
@@ -5,18 +5,26 @@ module ResourceDSL
   # config.batch_actions = true
   # config.scoped_collection_actions_if = -> { true }
   module ActsAsAsyncUpdate
-    def acts_as_async_update(model_class, attrs_to_update)
+    def acts_as_async_update(form_class)
       scoped_collection_action :async_update,
                                title: 'Update batch',
                                class: 'scoped_collection_action_button ui',
-                               form: attrs_to_update,
+                               form: form_class.form_data,
```
Comment (gigorok) [inline lib/resource_dsl/acts_as_async_update.rb:12]:
```suggestion
                               form: -> { form_class.form_data },
```

Comment (gigorok) [reply lib/resource_dsl/acts_as_async_update.rb:12]: following README of https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions form param should be lambda

Comment (Ivanov-Anton) [reply lib/resource_dsl/acts_as_async_update.rb:12]: +

File: app/admin/routing/routing_plans.rb [hunk 2]
```diff
@@ -7,14 +7,11 @@
...
-  acts_as_async_update('Routing::RoutingPlan',
-                       lambda do
-                         {
-                           sorting_id: Sorting.pluck(:name, :id),
-                           use_lnp: boolean_select,
-                           rate_delta_max: 'text'
-                         }
-                       end)
+  begin
+    acts_as_async_update BatchUpdateForm::RoutingPlan
```
Comment (gigorok) [inline app/admin/routing/routing_plans.rb:11]:
```suggestion
    acts_as_async_update 'BatchUpdateForm::RoutingPlan'
```
class should be provided as string to prevent loading class while booting app

File: app/admin/routing/routing_plans.rb [hunk 3]
```diff
@@ -7,14 +7,11 @@
...
+  rescue ActiveAdmin::DatabaseHitDuringLoad => e
+    Rails.logger.info 'Loading batch update'
+  end
```
Comment (gigorok) [inline app/admin/routing/routing_plans.rb:14]: remove rescue blocks

File: spec/features/equipment/gateways/batch_update_spec.rb [hunk 4]
```diff
@@ -0,0 +1,229 @@
...
+
+        it 'must be greater than or equal to zero' do
+          fill_in :acd_limit, with: -1
+          click_button :OK
+          expect(page).to have_selector '.flash', text: 'must be greater than or equal to 0.0'
+        end
+      end
+
+      context 'should have success' do
+        it 'change value lonely', :jobb do
```
Comment (Fivell) [inline spec/features/equipment/gateways/batch_update_spec.rb:117]: what does it mean "jobb" ?

Comment (Ivanov-Anton) [reply spec/features/equipment/gateways/batch_update_spec.rb:117]: > what does it mean "jobb" ?

I want to remove this before merging

File: app/models/batch_update_form/contractor.rb [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+        return true if Contractor.find_by(id: id)&.customers_auths&.any?
+      end
+      false
+    else
+      # find_each retrieves Contractors in batches of 1000 and yields them to the block one by one
+      Contractor.find_each do |contractor|
+        return true if contractor.customers_auths.any?
+      end
+      false
+    end
```
Comment (gigorok) [inline app/models/batch_update_form/contractor.rb:46]: this code have to much problems (complex, n+1)
def customers_auth_any?
  CustomersAuth.where(customer_id: selected_record || Contractor.select(:id)).any?
  end

File: app/models/batch_update_form/contractor.rb [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+  attribute :smtp_connection_id, type: :foreign_key, class_name: 'System::SmtpConnection'
+
+  validates :vendor, required_with: :customer
+
+  validate if: -> { customer_changed? || vendor_changed? } do
+    if customer == 'f' && vendor == 'f'
+      errors.add :base, I18n.t('activerecord.errors.models.contractor.vendor_and_customer')
+    elsif customer == 't'
+      errors.add :base, I18n.t('activerecord.errors.models.contractor.vendor_and_customer') if vendor == 't'
+    elsif vendor == 't'
```
Comment (gigorok) [inline app/models/batch_update_form/contractor.rb:20]: vendor should be already casted to boolean. why do you check with 't' or 'f' ?

File: spec/features/routing/customers_auths/batch_update_spec.rb [hunk 7]
```diff
@@ -0,0 +1,307 @@
...
+
+    context '"dst_number_max_length" should have error:' do
+      before { check :Dst_number_max_length }
+      it "can't be blank and is not a number" do
+        fill_in :dst_number_max_length, with: nil
+        click_button :OK
+        expect(page).to have_selector '.flash', text: "can't be blank"
+        expect(page).to have_selector '.flash', text: 'is not a number'
+      end
+
```
Comment (Fivell) [inline spec/features/routing/customers_auths/batch_update_spec.rb:158]: it is to expensive to run feature test for each attribute validator, also tests has not clear structure 

suggestion 
```
subject do
  fill_form
  click_button :OK
end 

context 'when form is invalid' do 
   let(:fill_form) do 
         
   end
end

context 'when form is valid' do
   let(:fill_form) do 
         
   end
end
end
```
