### PR TITLE
refs #754 fixed rendering index page from /bad_routing

### LINKED ISSUE #754: "Bad routing" index page don't rendering, if we have records only
[issue from community](https://community.yeti-switch.org/t/fail-report-bad-routing/218)

We need 'id' because ActiveAdmin fails to render table for records without id when it's model class has id in schema.

### PR DESCRIPTION
**Pull request by Ivanov-Anton**
closes #754
Summary: "Bad routing" index page don't rendering, if we have records only
logs: [FATAL]: ActionView::Template::Error (missing attribute: id)

We need 'id' because ActiveAdmin fails to render table for records without id when it's model class has id in schema.

### CODE REVIEW

File: spec/factories/reports/realtime/bad_routing.rb [hunk 1]
```diff
@@ -0,0 +1,14 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :bad_routing, class: Report::Realtime::BadRouting do
+    # DEFAULT_INTERVAL = 60 seconds
+    # >= 120.sec.ago                                                < 60.sec.ago
+    # <<<<<<<<<<<<<<<<|--------------------60.sec------------------|<<<<<<<<<<<< Creating record
+    # after 120 hidden|       interval thant can view records      |after creating, 60 seconds are hidden
+
+    time_start { 60.seconds.ago.utc } # this record will be showed during 60 second
```
Comment (gigorok) [inline spec/factories/reports/realtime/bad_routing.rb:10]: decrease count of seconds to 30 to prevent situation with flow specs

File: spec/factories/reports/realtime/bad_routing.rb [hunk 2]
```diff
@@ -0,0 +1,14 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :bad_routing, class: Report::Realtime::BadRouting do
+    # DEFAULT_INTERVAL = 60 seconds
+    # >= 120.sec.ago                                                < 60.sec.ago
+    # <<<<<<<<<<<<<<<<|--------------------60.sec------------------|<<<<<<<<<<<< Creating record
+    # after 120 hidden|       interval thant can view records      |after creating, 60 seconds are hidden
```
Comment (gigorok) [inline spec/factories/reports/realtime/bad_routing.rb:8]: remove comment

File: spec/factories/reports/realtime/not_authenticated.rb [hunk 3]
```diff
@@ -0,0 +1,13 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :not_authenticated, class: Report::Realtime::NotAuthenticated do
+    # DEFAULT_INTERVAL = 60 seconds
+    # >= 120.sec.ago                                                < 60.sec.ago
+    # <<<<<<<<<<<<<<<<|--------------------60.sec------------------|<<<<<<<<<<<< Creating record
```
Comment (gigorok) [inline spec/factories/reports/realtime/not_authenticated.rb:7]: remove comment

File: spec/factories/reports/realtime/not_authenticated.rb [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+    # after 120 hidden|       interval thant can view records      |after creating, 60 seconds are hidden
+
+    time_start { 60.seconds.ago.utc } # this record will be showed during 60 second
```
Comment (gigorok) [inline spec/factories/reports/realtime/not_authenticated.rb:10]: decrease to 30 seconds

File: spec/factories/reports/realtime/bad_routing.rb [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+
+    time_start { 60.seconds.ago.utc } # this record will be showed during 60 second
+    disconnect_initiator { DisconnectInitiator.find_by(id: 0) || create(:disconnect_initiator, :traffic_manager) }
+    customer_auth { create :customers_auth }
```
Comment (gigorok) [inline spec/factories/reports/realtime/bad_routing.rb:12]:
```suggestion
    association :customer_auth, factory: :customers_auth
```

File: app/models/report/realtime/bad_routing.rb [hunk 6]
```diff
@@ -154,6 +154,7 @@ class Report::Realtime::BadRouting < Report::Realtime::Base
   scope :detailed_scope, lambda { |length|
     l = length.to_i
```
Comment (gigorok) [inline app/models/report/realtime/bad_routing.rb:155]: remove this unused variable

File: spec/factories/disconnect_initiator.rb [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+      name { 'Traffic switch' }
+    end
+
+    trait :destination do
+      id { 2 }
+      name { 'Destination' }
+    end
+
+    trait :Origination do
+      id { 3 }
```
Comment (gigorok) [inline spec/factories/disconnect_initiator.rb:24]: will be good to have this magic numbers in constants defined in DisconnectInitiator model

example: ID_ORIGINATION = 3, ID_TRAFFIC_MANAGER = 0, etc

File: spec/factories/reports/realtime/bad_routing.rb [hunk 8]
```diff
@@ -0,0 +1,19 @@
+# frozen_string_literal: true
+
+FactoryBot.define do
+  factory :bad_routing, class: Report::Realtime::BadRouting do
```
Comment (gigorok) [inline spec/factories/reports/realtime/bad_routing.rb:4]:
```suggestion
  factory :bad_routing, class: Report::Realtime::BadRouting, parent: :cdr do
```

and remove copied trait :with_id_and_uuid

File: app/admin/reports/realtime/bad_routings.rb [hunk 9]
```diff
@@ -29,7 +29,7 @@
   controller do
     def scoped_collection
       length = params[:q][:time_interval_eq].to_i
```
Comment (gigorok) [inline app/admin/reports/realtime/bad_routings.rb:31]: remove this unused variable

File: app/admin/reports/realtime/not_authenticateds.rb [hunk 10]
```diff
@@ -17,7 +17,7 @@
   controller do
     def scoped_collection
       lenght = params[:q][:time_interval_eq].to_i
```
Comment (gigorok) [inline app/admin/reports/realtime/not_authenticateds.rb:19]: remove this unused variable

File: app/admin/reports/realtime/bad_routings.rb (hunk 9 above)
Comment (Ivanov-Anton) [reply app/admin/reports/realtime/bad_routings.rb:31]: only variable?

Comment (gigorok) [reply app/admin/reports/realtime/bad_routings.rb:31]: what do you mean ?

Comment (Ivanov-Anton) [reply app/admin/reports/realtime/bad_routings.rb:31]: or all line with params

Comment (gigorok) [reply app/admin/reports/realtime/bad_routings.rb:31]: yes, whole line
the method should looks like
```
def scoped_collection
  super.detailed_scope
end
```
