### PR TITLE
bug fix: for cdrs page, failed request when submit visible columns

### LINKED ISSUE #1363: CDRs visible columns 401
after changing visible columns on CDR page it loading infinitely:
image

Chrome debug tools shows 401 response:
image

application logs:
```
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Started GET "/cdrs?index_table_visible_columns%5B%5D=id&index_table_visible_columns%5B%5D=time_start&index_table_visible_columns%5B%5D=time_connect" for 1.2.4.5 at 2023-10-29 19:54:31 +0200
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Processing by CdrsController#index as JSON
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Parameters: {"index_table_visible_columns"=>["id", "time_start", "time_connect"]}
yeti-web[2077127]: [d726c8af-16e9-4f0a-a06d-cec341bec971] Completed 401 Unauthorized in 2ms (Views: 0.1ms | ActiveRecord: 0.3ms | Allocations: 760)
```

### PR DESCRIPTION
**Pull request by Ivanov-Anton**
## Description

added the `json` download links for CDR admin index page because the ActiveAdmin has build in
condition see below:

```
def restrict_format_access!
  unless request.format.html?
    presenter = active_admin_config.get_page_presenter(:index)
    download_formats = (presenter || {}).fetch(:download_links, active_admin_config.namespace.download_links)
    unless build_download_formats(download_formats).include?(request.format.symbol)
      raise ActiveAdmin::AccessDenied.new(current_active_admin_user, :index)
    end
  end
end
```

so download_formats it is actually download_links from index page

## Additional links

closes #1363

### CODE REVIEW

File: lib/active_admin/index_as_table_visible_columns/controller.rb [hunk 1]
```diff
@@ -8,26 +8,13 @@ module Controller
...
           if columns_visibility?
-            set_visible_columns
             @visible_columns = []
             if current_admin_user.visible_columns[visible_columns_key].is_a?(Array)
               @visible_columns = current_admin_user.visible_columns[visible_columns_key]
             end
           end
         end
 
-        def set_visible_columns
```
Comment (Ivanov-Anton) [inline lib/active_admin/index_as_table_visible_columns/controller.rb:19]: removed because to use render within "before" filter is not good idea instead of this I will use `visible_index_columns` collection action
